# Generated by Django 5.0.6 on 2024-06-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_predict', '0002_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam',
            field=models.CharField(choices=[('행시', '5급공채/행정고시'), ('입시', '입법고시'), ('칠급', '7급공채'), ('프모', '프라임모의고사')], max_length=2, unique=True),
        ),
    ]
