# Generated by Django 5.0.6 on 2024-06-18 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_predict', '0003_alter_exam_exam'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('exam', 'unit', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('exam', 'unit')},
        ),
    ]
