# Generated by Django 5.0.6 on 2024-06-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_predict', '0004_alter_department_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='round',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answercount',
            name='exam',
            field=models.CharField(choices=[('행시', '5급공채/외교원/지역인재 7급'), ('입시', '입법고시'), ('칠급', '7급공채/민간경력 5·7급'), ('프모', '프라임 모의고사')], max_length=2),
        ),
        migrations.AlterField(
            model_name='answercountlowrank',
            name='exam',
            field=models.CharField(choices=[('행시', '5급공채/외교원/지역인재 7급'), ('입시', '입법고시'), ('칠급', '7급공채/민간경력 5·7급'), ('프모', '프라임 모의고사')], max_length=2),
        ),
        migrations.AlterField(
            model_name='answercountmidrank',
            name='exam',
            field=models.CharField(choices=[('행시', '5급공채/외교원/지역인재 7급'), ('입시', '입법고시'), ('칠급', '7급공채/민간경력 5·7급'), ('프모', '프라임 모의고사')], max_length=2),
        ),
        migrations.AlterField(
            model_name='answercounttoprank',
            name='exam',
            field=models.CharField(choices=[('행시', '5급공채/외교원/지역인재 7급'), ('입시', '입법고시'), ('칠급', '7급공채/민간경력 5·7급'), ('프모', '프라임 모의고사')], max_length=2),
        ),
        migrations.AlterField(
            model_name='department',
            name='exam',
            field=models.CharField(choices=[('행시', '5급공채/외교원/지역인재 7급'), ('입시', '입법고시'), ('칠급', '7급공채/민간경력 5·7급'), ('프모', '프라임 모의고사')], max_length=2),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam',
            field=models.CharField(choices=[('행시', '5급공채/외교원/지역인재 7급'), ('입시', '입법고시'), ('칠급', '7급공채/민간경력 5·7급'), ('프모', '프라임 모의고사')], max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='exam',
            field=models.CharField(choices=[('행시', '5급공채/외교원/지역인재 7급'), ('입시', '입법고시'), ('칠급', '7급공채/민간경력 5·7급'), ('프모', '프라임 모의고사')], max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='exam',
            field=models.CharField(choices=[('행시', '5급공채/외교원/지역인재 7급'), ('입시', '입법고시'), ('칠급', '7급공채/민간경력 5·7급'), ('프모', '프라임 모의고사')], max_length=2),
        ),
        migrations.AlterField(
            model_name='unit',
            name='exam',
            field=models.CharField(choices=[('행시', '5급공채/외교원/지역인재 7급'), ('입시', '입법고시'), ('칠급', '7급공채/민간경력 5·7급'), ('프모', '프라임 모의고사')], max_length=2),
        ),
    ]
