# Generated by Django 5.0.6 on 2024-06-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_predict', '0005_exam_round_alter_answercount_exam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam',
            field=models.CharField(choices=[('행시', '5급공채/외교원/지역인재 7급'), ('입시', '입법고시'), ('칠급', '7급공채/민간경력 5·7급'), ('프모', '프라임 모의고사')], max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('exam', 'round')},
        ),
    ]
