# Generated by Django 5.0.6 on 2024-06-19 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_predict', '0006_alter_exam_exam_alter_exam_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='unit',
        ),
    ]
