# Generated by Django 5.0.6 on 2024-06-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_predict', '0007_remove_location_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentanswer',
            old_name='is_confirmed',
            new_name='all_submitted',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='answer_eoneo',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='answer_heonbeob',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='answer_jaryo',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='answer_sanghwang',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='eoneo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='eoneo_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='heonbeob',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='heonbeob_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='jaryo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='jaryo_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='sanghwang',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='sanghwang_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
