# Generated by Django 5.0.6 on 2024-06-19 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_predict', '0008_rename_is_confirmed_studentanswer_all_submitted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='all_submitted',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='eoneo_submitted',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='heonbeob_submitted',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='jaryo_submitted',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='sanghwang_submitted',
        ),
    ]
