# Generated by Django 5.0.6 on 2024-06-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_predict', '0009_remove_studentanswer_all_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
