# Generated by Django 5.0.6 on 2024-06-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_predict', '0011_studentanswer_eoneo_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='submittedanswer',
            name='answer',
            field=models.IntegerField(default=0),
        ),
    ]
