# Generated by Django 5.0.6 on 2024-06-22 23:01

import a_predict.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_predict', '0012_alter_department_options_alter_unit_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(choices=a_predict.models.year_choice, default=2024)),
                ('exam', models.CharField(choices=[('행시', '5급공채/외교원/지역인재 7급'), ('입시', '입법고시'), ('칠급', '7급공채/민간경력 5·7급'), ('프모', '프라임 모의고사')], max_length=2)),
                ('round', models.IntegerField(default=0)),
                ('heonbeob', models.TextField(default='')),
                ('eoneo', models.TextField(default='')),
                ('jaryo', models.TextField(default='')),
                ('sanghwang', models.TextField(default='')),
            ],
            options={
                'db_table': 'a_predict_official_answer',
                'unique_together': {('year', 'exam', 'round')},
            },
            bases=(models.Model, a_predict.models.ChoiceMethod),
        ),
    ]
