# Generated by Django 5.0.6 on 2024-06-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_predict', '0013_officialanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialanswer',
            name='answer',
            field=models.JSONField(default=dict),
        ),
    ]
