# Generated by Django 5.0.6 on 2024-06-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_predict', '0014_officialanswer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='answer',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='answer_confirmed',
            field=models.JSONField(default=dict),
        ),
    ]
