# Generated by Django 5.0.6 on 2024-06-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_predict', '0015_studentanswer_answer_studentanswer_answer_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='answer_count',
            field=models.JSONField(default=dict),
        ),
    ]
