# Generated by Django 5.0.6 on 2024-06-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_predict', '0017_statistics_participants_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticsvirtual',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
