# Generated by Django 5.0.6 on 2024-06-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_predict', '0018_statisticsvirtual_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
