# Generated by Django 5.0.6 on 2024-06-14 05:38

import a_police.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=a_police.models.year_choice, default=2024)),
                ('exam', models.CharField(choices=[('경위', '경위공채')], default='경위', max_length=2)),
                ('subject', models.CharField(choices=[('형사', '형사법'), ('헌법', '헌법'), ('경찰', '경찰학'), ('범죄', '범죄학'), ('행법', '행정법'), ('행학', '행정학'), ('민법', '민법총칙'), ('세법', '세법개론'), ('회계', '회계학'), ('상법', '상법총칙'), ('경제', '경제학'), ('통계', '통계학'), ('재정', '재정학'), ('정보', '정보보호론'), ('시네', '시스템네트워크보안'), ('데베', '데이터베이스론'), ('통신', '통신이론'), ('소웨', '소프트웨어공학')], default='형사', max_length=2)),
                ('department', models.CharField(choices=[('전체', '전체'), ('일반', '일반'), ('세무회계', '세무회계'), ('사이버', '사이버')], default='전체', max_length=5)),
                ('category', models.CharField(choices=[('공통', '공통'), ('필수', '필수'), ('선택', '선택')], default='공통', max_length=5)),
                ('number', models.IntegerField(choices=a_police.models.number_choice, default=1)),
                ('answer', models.IntegerField()),
                ('question', models.TextField()),
                ('data', models.TextField()),
            ],
            options={
                'ordering': ['-year', 'id'],
            },
        ),
    ]
