# Generated by Django 5.0.6 on 2024-06-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_police', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='primeanswercount',
            name='count_multiple',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='primeanswercount',
            name='count_total',
            field=models.IntegerField(default=0),
        ),
    ]
