# Generated by Django 5.0.6 on 2024-06-26 02:10

import a_score.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('exam', models.CharField(choices=[('행시', '5급공채/외교원/지역인재 7급'), ('입시', '입법고시'), ('칠급', '7급공채/민간경력 5·7급'), ('프모', '프라임 PSAT 모의고사'), ('프경', '프라임 경위공채 모의고사')], max_length=2)),
                ('unit', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=128)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('exam', 'unit', 'department')},
            },
            bases=(models.Model, a_score.models.ChoiceMethod),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('exam', models.CharField(choices=[('행시', '5급공채/외교원/지역인재 7급'), ('입시', '입법고시'), ('칠급', '7급공채/민간경력 5·7급'), ('프모', '프라임 PSAT 모의고사'), ('프경', '프라임 경위공채 모의고사')], max_length=2)),
                ('round', models.IntegerField(default=0)),
                ('page_opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam_finished_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('score_opened_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('exam', 'round')},
            },
            bases=(models.Model, a_score.models.ChoiceMethod),
        ),
        migrations.CreateModel(
            name='PrimeAnswerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField(choices=a_score.models.year_choice, default=2024)),
                ('exam', models.CharField(choices=[('행시', '5급공채/외교원/지역인재 7급'), ('입시', '입법고시'), ('칠급', '7급공채/민간경력 5·7급'), ('프모', '프라임 PSAT 모의고사'), ('프경', '프라임 경위공채 모의고사')], max_length=2)),
                ('round', models.IntegerField(default=0)),
                ('subject', models.CharField(choices=[('헌법', '헌법'), ('언어', '언어논리'), ('자료', '자료해석'), ('상황', '상황판단'), ('형사', '형사법'), ('경찰', '경찰학'), ('범죄', '범죄학'), ('행법', '행정법'), ('행학', '행정학'), ('민법', '민법총칙'), ('세법', '세법개론'), ('회계', '회계학'), ('상법', '상법총칙'), ('경제', '경제학'), ('통계', '통계학'), ('재정', '재정학'), ('정보', '정보보호론'), ('시네', '시스템네트워크보안'), ('데베', '데이터베이스론'), ('통신', '통신이론'), ('소웨', '소프트웨어공학')], max_length=2)),
                ('number', models.IntegerField()),
                ('answer', models.IntegerField(blank=True, null=True)),
                ('count_1', models.IntegerField(default=0)),
                ('count_2', models.IntegerField(default=0)),
                ('count_3', models.IntegerField(default=0)),
                ('count_4', models.IntegerField(default=0)),
                ('count_5', models.IntegerField(default=0)),
                ('count_0', models.IntegerField(default=0)),
                ('count_None', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '성적 예측 답안 개수(전체)',
                'verbose_name_plural': '성적 예측 답안 개수(전체)',
                'db_table': 'a_score_prime_answer_count',
                'unique_together': {('year', 'exam', 'round', 'subject', 'number')},
            },
            bases=(models.Model, a_score.models.ChoiceMethod),
        ),
        migrations.CreateModel(
            name='PrimeOfficialAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(choices=a_score.models.year_choice, default=2024)),
                ('exam', models.CharField(choices=[('행시', '5급공채/외교원/지역인재 7급'), ('입시', '입법고시'), ('칠급', '7급공채/민간경력 5·7급'), ('프모', '프라임 PSAT 모의고사'), ('프경', '프라임 경위공채 모의고사')], max_length=2)),
                ('round', models.IntegerField(default=0)),
                ('answer', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'a_score_prime_official_answer',
                'unique_together': {('year', 'exam', 'round')},
            },
            bases=(models.Model, a_score.models.ChoiceMethod),
        ),
        migrations.CreateModel(
            name='PrimeStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(choices=a_score.models.year_choice, default=2024)),
                ('exam', models.CharField(choices=[('행시', '5급공채/외교원/지역인재 7급'), ('입시', '입법고시'), ('칠급', '7급공채/민간경력 5·7급'), ('프모', '프라임 PSAT 모의고사'), ('프경', '프라임 경위공채 모의고사')], max_length=2)),
                ('round', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=20)),
                ('serial', models.CharField(max_length=10)),
                ('unit', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=128)),
                ('subject', models.JSONField(default=dict)),
                ('password', models.IntegerField()),
            ],
            options={
                'verbose_name': '수험 정보',
                'verbose_name_plural': '수험 정보',
                'db_table': 'a_score_prime_student',
                'unique_together': {('year', 'exam', 'round', 'serial')},
            },
            bases=(models.Model, a_score.models.ChoiceMethod),
        ),
        migrations.CreateModel(
            name='PrimeStudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('answer', models.JSONField(default=dict)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='a_score.primestudent')),
            ],
            options={
                'verbose_name': '제출 답안',
                'verbose_name_plural': '제출 답안',
                'db_table': 'a_score_prime_student_answer',
            },
            bases=(models.Model, a_score.models.ChoiceMethod),
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.JSONField(default=dict)),
                ('rank_total', models.JSONField(default=dict)),
                ('rank_department', models.JSONField(default=dict)),
                ('participants_total', models.JSONField(default=dict)),
                ('participants_department', models.JSONField(default=dict)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='a_score.primestudent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('exam', models.CharField(choices=[('행시', '5급공채/외교원/지역인재 7급'), ('입시', '입법고시'), ('칠급', '7급공채/민간경력 5·7급'), ('프모', '프라임 PSAT 모의고사'), ('프경', '프라임 경위공채 모의고사')], max_length=2)),
                ('unit', models.CharField(max_length=128)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('exam', 'unit')},
            },
            bases=(models.Model, a_score.models.ChoiceMethod),
        ),
        migrations.CreateModel(
            name='PrimeStudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='a_score.primestudent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prime_student_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'a_score_prime_student_record',
                'unique_together': {('user', 'student')},
            },
        ),
    ]
